#
# Integration Test Config: Require Guests to Login
#

listenAddressSingleHTTPFrontend: 0.0.0.0:1337

logLevel: "DEBUG"
checkForUpdates: false

# Require guests to login
authRequireGuestsToLogin: true

# Enable local user authentication
authLocalUsers:
  enabled: true
  users:
    - username: "alice"
      usergroup: "admins"
      password: "$argon2id$v=19$m=65536,t=4,p=6$ORxyZZGW6E3FWZnbQmHJ9Q$BzIOWeXry/BZ6+JV1T4UASBnebVLB9QJ4f5TmUPXsg4" # notsecret: password

    - username: "bob"
      usergroup: "users"
      password: "$argon2id$v=19$m=65536,t=4,p=6$ORxyZZGW6E3FWZnbQmHJ9Q$BzIOWeXry/BZ6+JV1T4UASBnebVLB9QJ4f5TmUPXsg4" # notsecret: password

accessControlLists:
  - name: "admin"
    matchUsergroups: ["admins"]
    addToEveryAction: true
    permissions:
      view: true
      exec: true
      logs: true
      kill: true

  - name: "users"
    matchUsergroups: ["users"]
    addToEveryAction: true
    permissions:
      view: true
      exec: false
      logs: false
      kill: false

# Simple actions for testing
actions:
- title: Ping Google.com
  shell: ping google.com -c 1
  icon: ping

- title: sleep 2 seconds
  shell: sleep 2
  icon: "&#x1F971"

